containers:
  basic:
    opencfd-openfoam:
      os:
        distro: ubuntu
        version: 24.04
      mpi:
        implementation: openmpi
        version: 4.1.5
      framework:
        definition: com-openfoam
        version: 2312
        git_ref: default
  projects:
    meshingo:
      base_container: opencfd-openfoam
      definition: meshingo.def
      build_args:
        branch:
          - main

pull:
  try_to_pull: true
  protocol: "oras"
  scope: "ghcr.io/foamscience"
